### ISSUE TITLE
Bug: Cannot open the plugin 

### ISSUE THREAD

**Issue by YIRU69** [Vaccarini-Lorenzo/MagicCalendar#27]
```
Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\1\.obsidian\plugins\magic-calendar\.base64Media.json'
```
Cannot open the plugin.

And could you add a command in the plugin, I don't like use it open the plugin on the side.

**Comment by Vaccarini-Lorenzo** [comment]
Hello, can you please provide the steps to replicate the problem?

**Comment by Vaccarini-Lorenzo** [comment]
Hi there! 
Thank you for opening this issue: Apparently, the latest release did not include in the zip file the .base64Media.json. 
Everything should work fine now.
