### ISSUE TITLE
[Suggestion] keyword/key symbol for literal events

### ISSUE THREAD

**Issue by paraversal** [Vaccarini-Lorenzo/MagicCalendar#33]
Hi! This project is really cool. I was wondering whether it was possible to implement a second mode of event input where, if you start a line with a specific character/keyword, it will use the whole line as the event title.
So currently, if you put in, say "❗Lecture Quiz 10 next tue", the event will just be "lecture quiz". My idea was that, say we set "&" as the key symbol, "❗Lecture Quiz 10 next tue" would still be "lecture quiz", but "&❗Lecture Quiz 10 next tue" would be "❗Lecture Quiz 10".
Looking forward to your reply.

**Comment by Vaccarini-Lorenzo** [comment]
Hi there, thank you for opening this issue: Every feedback and suggestion is much appreciated! 
The feature you're suggesting is surely feasible (fun fact: one of the very first versions of the project worked just like that) and I'll implement it as soon as possible. Unfortunately, at the moment I'm very busy and I don't know when I'll have the chance to work on it, I'll keep you posted!
Lorenzo

**Comment by Vaccarini-Lorenzo** [comment]
Hi @paraversal, I had a spare hour and tried a quick demo implementation. Is this what you had in mind?
<img width="650" src="https://raw.githubusercontent.com/Vaccarini-Lorenzo/MagicCalendar/custom_symbol_development/materials/Issue32.gif">
If you want to try it just clone the [custom_symbol_development](https://github.com/Vaccarini-Lorenzo/MagicCalendar/tree/custom_symbol_development) branch!
Lorenzo

**Comment by Vaccarini-Lorenzo** [comment]
Hey there, the beta feature has been implemented in the 1.1.9 version. 
Feel free to give me feedback.
Lorenzo

**Comment by Vaccarini-Lorenzo** [comment]
Close due to inactivity. Feel free to reopen it if anything changes.
